name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
#   pull_request:
#     types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    uses: socheatsok78/uses/.github/workflows/docker-buildx-bake.yml@main
    permissions:
      contents: read
      packages: write
    with:
      permit-push: ${{ github.event_name != 'pull_request' }}
